### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by jonferreira** [bestlong/node-red-contrib-mssql-plus#17]
Hi,

I'm feeling like a complete noob and I'm sure it's me missing something silly but for the life on me,I can't connect to a SQL server with this node.

I have a "remote" SQL server I can access with Navicat with sql.mydomain.com\instance,50002 but failing to translate this into node config.

I've tried with

server: sql.mydomain.com\instance
port: 50002

and 

server: sql.mydomain.com\instance,50002
port: 1433

but all I get is timeout errors...

Can someone give me a hand please?

**Comment by bestlong** [comment]
Hi @jonferreira 
I don`t have Navicat. but can you try

server: sql.mydomain.com\instance
port: 1433

**Comment by jonferreira** [comment]
Thanks.

Think the server may have upd1444 closed or something cuz I just couldn't access it via named instance.

In the end managed to get going with just sql.mydomain.com and port: 50002.

Been using it and so far I love it, great job @bestlong!
