### ISSUE TITLE
suggestion: be able to handle multiple SELECT queries

### ISSUE THREAD

**Issue by jonferreira** [bestlong/node-red-contrib-mssql-plus#18]
Hi,

Just a quick suggestion I'd love to see it being implemented.

Add the ability to handle multiple SELECT queries, e.g.

msg.payload =

```
SELECT * FROM Customers;
SELECT * FROM CustomersDetails;
```

In Studio Management or Navicat this will execute 2 SELECT queries and return each one.

Would be great to have a similar behaviour here, maybe having the node return these as an array:

msg.payload = [
[query 1 results array],[query 2 results array]
]

**Comment by Steve-Mcl** [comment]
This node already supports multiple queries.

![image](https://user-images.githubusercontent.com/44235289/80093586-a8945400-855c-11ea-9129-fb4d1ac72ec6.png)


![image](https://user-images.githubusercontent.com/44235289/80093548-99ada180-855c-11ea-8427-a7c3f16d4b1f.png)
