### ISSUE TITLE
New connection per node?

### ISSUE THREAD

**Issue by NeltherGP** [bestlong/node-red-contrib-mssql-plus#26]
I want to know if a new connection is created for each node or if a single connection is shared between many nodes.

**Comment by bestlong** [comment]
this package have two node. MSSQL node and MSSQL-CN node.
MSSQL node for query 
MSSQL-CN for connection pool
many MSSQL node can use common MSSQL-CN node.

**Comment by NeltherGP** [comment]
Thanks, I confirmed this with sp_who2 query and executing a test sp with a delay inside.
