### ISSUE TITLE
Stored Procedures

### ISSUE THREAD

**Issue by Humphaz** [bestlong/node-red-contrib-mssql-plus#27]
Hi,

Is there any way of supporting the execution of stored procedures.

I notice in the Node.JS MSSQL that stored procedures are called in a different way, is there support for it node-red-contrib-mssql-plus.

Best Regards,

Glyn

**Comment by pedrossag** [comment]
Hi, 
a temporary workaround could be the exec node that calls a batch script. 
The batch runs SQLCMD that executes the SP. 

Regards, 
Hannes

**Comment by Steve-Mcl** [comment]
No need for work around - stored procedures work already...

![image](https://user-images.githubusercontent.com/44235289/80095178-6ae4fa80-855f-11ea-946a-9e972a7d87bb.png)


![image](https://user-images.githubusercontent.com/44235289/80095040-2eb19a00-855f-11ea-8d6e-38bf421fc10f.png)
