### ISSUE TITLE
SQL Editor area not filling available space. 

### ISSUE THREAD

**Issue by damonroberts95** [bestlong/node-red-contrib-mssql-plus#37]
I've recently updated from 0.3.2. to 0.5.0. and noticed the query editor portion of the node settings has shrunk significantly. This appears to be because the sidebar leaves space for the parameter 'editor' mode in 0.5.0, even when it isn't visible. It seems like the `oneditresize` function doesn't take into account whether the second editor is visible and leaves space for it regardless. This makes it hard to deal with more complex queries. 

Below are screenshots of 0.5.0 and 0.3.2

![image](https://user-images.githubusercontent.com/62603811/91142084-1e91fe80-e6a8-11ea-8aa5-03672d8b343d.png)
![image](https://user-images.githubusercontent.com/62603811/91142049-10dc7900-e6a8-11ea-8df1-0e7d76ebf214.png)

**Comment by Steve-Mcl** [comment]
Hi @damonroberts95 , thanks for taking the time to raise an issue.

I will see if I can make the re-sizing of elements smarter next time i am in the code.

Cheers.

**Comment by Steve-Mcl** [comment]
I have made some UI improvements in V0.5.1 (44f0dc3) 

- add "none" option to parameters
- make query window resize to available space
- add expand button to further increase query editing size

 I'd appreciate it if you update from NPM (or via node-red pallete when it appears)

**Comment by damonroberts95** [comment]
Spot on, works perfectly, nice one! Better service than if it was paid for!

![image](https://user-images.githubusercontent.com/62603811/91171405-544bdd00-e6d2-11ea-98d9-81e191a65bb8.png)

**Comment by Steve-Mcl** [comment]
did you test the expand button (top right of query editor)?
Is that working too?
If so, please comment and close :+1:

**Comment by damonroberts95** [comment]
I did, also working perfectly (Forgot to mention it as I don't think I've ever actually used it before!)

**Comment by damonroberts95** [comment]
As of updating to 0.6.2 the parameters editor window no longer hides itself if set to none.

![image](https://user-images.githubusercontent.com/62603811/104443730-b4162800-558e-11eb-8e1c-20a15b512022.png)

**Comment by Steve-Mcl** [comment]
Oh. Dang. Well spotted. Not sure how I have managed that. Will look into it asap. Thanks. 

Ps, if you could check the browser Devtools (F12) and let me know if there are any errors occuring when you select between parameters and none parameters, that would be helpful. Thanks.

**Comment by damonroberts95** [comment]
I'm only getting `[Violation] Forced reflow while executing JavaScript took 69ms` when opening the dropdown. Nothing the rest of the time.

Everything else seems to be working well!

**Comment by Steve-Mcl** [comment]
Ok cheers. I'll look into it soon. Sorry for the troubles.

**Comment by Steve-Mcl** [comment]
Should be fixed in v0.6.3
