### ISSUE TITLE
Failover Partner connections.

### ISSUE THREAD

**Issue by globaluk** [bestlong/node-red-contrib-mssql-plus#44]
I've got a clustered database to connect to, using the FailoverPartner attribute in the connection string, detailed here : https://www.connectionstrings.com/sqlconnection/database-mirroring/

Is there a way to do this ?

Thanks
Simon

**Comment by Steve-Mcl** [comment]
Hi. Unfortunately the underlying driver doesn't support this depreciated feature (see [this issue](https://github.com/tediousjs/tedious/issues/315)

I have successfully connected to a traditional SQL cluster (using the cluster address/hostname).
