### ISSUE TITLE
Comment -  tediousjs / node-mssql now at beta 3

### ISSUE THREAD

**Issue by harmonic7** [bestlong/node-red-contrib-mssql-plus#46]
Just a comment - I noticed that there is now this available: https://github.com/tediousjs/node-mssql/tree/v7.0.0-beta.3
  In-case you weren't aware

**Comment by Steve-Mcl** [comment]
Hi, yes, I was aware, however NPM is still on 6.x.x

AFAIK, the changes in alpha ~ beta are minimal so you can update that yourself if you wish to test it.

But as it is now actually a beta, hopefully it wont be long till a 7.x.x release

**Comment by Steve-Mcl** [comment]
FYI, I have just published `node-red-contrib-mssql-plus@0.7.0-beta.4` that targets the beta.

I would be grateful for any feedback if you decide to test it?

**Comment by Steve-Mcl** [comment]
@harmonic7, with mssql at V0.7.0 I have now updated master branch to v0.7.0 and is now published to NPM / flows lib.

I will close this and other issues but please do test and feedback any issues.

Thanks for your support
