### ISSUE TITLE
node.queryOptType should be node.paramsOptType

### ISSUE THREAD

**Issue by stephanlotter** [bestlong/node-red-contrib-mssql-plus#49]
If found a bug in mssql.js at the following line:

https://github.com/bestlong/node-red-contrib-mssql-plus/blob/4c9d4c1ae4984a3c7da63774bf47479bc4ee63a2/src/mssql.js#L595

It should be `node.paramsOptType` in stead of `node.queryOptType`:

`} else if(!node.paramsOptType || node.paramsOptType == "editor") {`

The bug causes parameter values passed in msg to not work.

**Comment by Steve-Mcl** [comment]
Hi, thanks for the feedback. 

I believe this has been corrected in the 0.7.0-beta.4 version which will be released as 0.7.0 very soon

I will leave this open for now. I would appreciate it if you could feedback if everything is ok once it has been updated? 

thanks.

**Comment by stephanlotter** [comment]
Looks great! Thanks!

**Comment by Steve-Mcl** [comment]
Cheers  Can we close this issue now?
