### ISSUE TITLE
Catch errors

### ISSUE THREAD

**Issue by pate313373** [bestlong/node-red-contrib-mssql-plus#5]
Hi bestlong!

Sorry for bothering you again, but you are the only one who is still out there on mssql for node-red. - So your work is most appreciated!

I've just noticed, that a catch-node does not catch erros of a mssql node, maybe you could implement to throw an exception by any chance?

BR
pate

**Comment by Steve-Mcl** [comment]
Addressed in V0.2.1

![image](https://user-images.githubusercontent.com/44235289/61793359-dfdfa400-ae16-11e9-9aca-74adc7f7d957.png)
