### ISSUE TITLE
Examples of using a connection node? Cannot even find the node in the palette

### ISSUE THREAD

**Issue by werkstrom** [bestlong/node-red-contrib-mssql-plus#50]
Sorry for perhaps being a noob question, but how can I setup a common connection that opens in the beginning of a flow. Will be used for a lot of operations/queries and then closed at the end of the flow. I cannot find an example and honestly don't know how to implement it. I cannot even find the CN-node in my palette (it shows up as installed but I cannot find it to drag it into my flow). Have tried in Azure web app, Azure Ubuntu VM and on my Home Assistant with the same result :-( Can I be missing some prerequisite
![chrome_ksOmyon3GV](https://user-images.githubusercontent.com/13434693/118360446-dee9aa80-b587-11eb-9946-c53a0ea54a37.jpg)
![chrome_8sRrMaIINA](https://user-images.githubusercontent.com/13434693/118360448-e1e49b00-b587-11eb-9783-604fa7e8fdb3.jpg)

?

**Comment by Steve-Mcl** [comment]
> how can I setup a common connection

You add an MSSQL node to the flow, open it, then setup a connection.

![image](https://user-images.githubusercontent.com/44235289/118361015-6384fa80-b581-11eb-8e04-f767bff59d30.png)


Then when you add more MSSQL nodes to the editor, that common config is available to all other MSSQL nodes.

This is not unique to the MSSQL node (this is how node-red does shared config nodes)

If you have further questions about usage, the best place to start is the [node-red fourm](https://discourse.nodered.org/) (in fact most of your questions will have been asked and answered - use the forum search before posting)
