### ISSUE TITLE
Using split in combination with MSSQL-plus and azureSQL

### ISSUE THREAD

**Issue by Marklundarn** [bestlong/node-red-contrib-mssql-plus#51]
First of all. Great work with this node. Easy to use and still versatile.
I might however have push it to it's limit in this scenario and like to discuss it. 

This is the scenario that im testing. 
![image](https://user-images.githubusercontent.com/55854859/118470835-5d208b00-b707-11eb-8a11-6fef20566945.png)

I want to be able to run a query for each row (object in my array) but im facing the issue 
`Resource ID : 1. The request limit for the database is 30 and has been reached. See 'http://go.microsoft.com/fwlink/?LinkId=267637' for assistance.
`

From what i can understand the node is opening a connection for each query that runs and that would totally make sense. 
In this case it does however create problems with limits towards Azure. 

What i think could solve this problem would be if we actually open the connection --> run alla queries --> close connection. 
Something like this
![image](https://user-images.githubusercontent.com/55854859/118472188-d8367100-b708-11eb-8526-5a85d27bcefe.png)

I have found a couple of workarounds like concatenate the complete query and then run. That technically solves the issue but makes the flow harder to follow and maintain. 

Is there a way to control the opening and closing of the connection manually? 

A example flow to recreate the issue 
[flows.zip](https://github.com/bestlong/node-red-contrib-mssql-plus/files/6493176/flows.zip)

**Comment by Steve-Mcl** [comment]
Hi @Marklundarn how many queries are executed from your object?  I assume more than 30? 

Reading up on the issue it's to do with concurrent requests and it is a limitation set by your azure package. For example if you moved up from the basic package you would get more concurrent requests. 

Are these queries quite large & do they take some time to respond? If so & you are in no major hurry to get the answers back you could use a delay node-set to rate limit queries to 1 per second.   

Also I haven't had a chance to look at your flow, could you post an example of a couple of queries? Perhaps it's just a case of building a dynamic where clause to perform just one query? Maybe a stored procedure and TVP would be more suitable?

**Comment by Marklundarn** [comment]
Hi, 

Yeah, im running about 250 as a test case. Actually thought "request" was the same as "opened connections" but that doesn't seem to be the case.  With the limitations of azure SQL i think the only viable solution is to concatenate into one big request. Thanks for you input! :) 


/Jens

**Comment by Marklundarn** [comment]
Hi, 

After reading up a bit more on how mssql seems to handle request/workers. It do indeed seem like 1 connection instance will always be using at least 1 worker(request) (maybe more depending on the Max DOP setting on dbServer) . 

That means that if we are opening a connection for each "run" of the mssql-node and closing the connection instance after the query are done we'll risk ending upp with multiple instances of connections opened at the same time. Each connection instance using a minimum of 1 request/worker slot. This would max out the worker/requests slot almost instantly and azure would reject our connections. But if open a single connection instance and re-use it to execute our queries and then closing when all queries are executed. We would only be using 1 connection which would mean less workers/requests towards azure even with the same amount of queries. I also think that this approach would remove som overhead created by opening and closing connections for each query. 

Do understand that this isn't some minor thing to do but just wanted to contribute with my thoughs on the issue :)

**Comment by UNOPARATOR** [comment]
@Marklundarn; since the limitation is regarding your **_Azure SQL Database Resource Limits_**, you might consider adding a delay node _(set as a Rate Limiter)_ or maybe try the [node-red-contrib-semaphore](https://flows.nodered.org/node/node-red-contrib-semaphore) node instead.

**Comment by Marklundarn** [comment]
> @Marklundarn; since the limitation is regarding your **_Azure SQL Database Resource Limits_**, you might consider adding a delay node _(set as a Rate Limiter)_ or maybe try the [node-red-contrib-semaphore](https://flows.nodered.org/node/node-red-contrib-semaphore) node instead.

Thanks! I'll look into that :)
