### ISSUE TITLE
Wrong Variable in Debug Window on Connect and Disconnect Database

### ISSUE THREAD

**Issue by patricks89** [bestlong/node-red-contrib-mssql-plus#52]
I had an Error in Debug Window with another node, so i checked Debug Window. During redeploy i saw that on Disconnect the DB (redeploy) the User is declared as Servername.
Node-Red: V1.35
MSSQL-Plus: V0.7.0
Database: MSSQL
![image](https://user-images.githubusercontent.com/52099317/119256326-766e7f00-bbc0-11eb-97e8-b104a4c6ac43.png)

**Comment by Steve-Mcl** [comment]
Well spotted.

Thanks for the feedback.

node-red-contrib-mssql-plus@0.7.1 now in NPM
