### ISSUE TITLE
error connecting to ms sql server 2019 linux / docker

### ISSUE THREAD

**Issue by na-am** [bestlong/node-red-contrib-mssql-plus#54]
Hi
i've no success to connect to a linux ms sql server in a docker container
besides, i can connect from a windows client to the ms sql server and also from Azure Data Studio (MacOS)

what i noticed is, that the windows client shows me no instance name for the linux ms sql server, just a servername (mssqlserver)
that page says, that the linux version has no instance name:
https://stackoverflow.com/questions/41695344/how-can-i-create-named-instance-of-microsoft-sql-server-on-ubuntu
could that be the problem?

error msg with instance name 'mssqlserver':   _Failed to connect to ip\mssqlserver_
error msg w/o an instance name:  _invalid syntax near '-'._

thanks

**Comment by Steve-Mcl** [comment]
Hi. 

Can you show a screenshot of the working connection details from azure data studio and a screenshot of what you enter into the node connection setup?

**Comment by na-am** [comment]
Azure Data Studio query
![image](https://user-images.githubusercontent.com/47410115/125062459-b1643d80-e0ae-11eb-8cec-66b5d15db935.png)

Node-red settings:
![image](https://user-images.githubusercontent.com/47410115/125062870-259ee100-e0af-11eb-9016-498b94a938fe.png)

**Comment by Steve-Mcl** [comment]
You didnt show me the connection detail for Data Studio - never mind. 

the port number is possibly not 1433

Look in the console for "listening"...

```
2021-07-07 09:29:11.38 spid19s     Server is listening on [ 'any' <ipv6> 1433].                                                                                                                                                                                                                                                                                                                                                      
2021-07-07 09:29:11.38 spid19s     Server is listening on [ 'any' <ipv4> 1433].                                                                                                                                                                                                                                                                                                                                                      
2021-07-07 09:29:11.39 Server      Server is listening on [ ::1 <ipv6> 1434].                                                                                                                                                                                                                                                                                                                                                        
2021-07-07 09:29:11.40 Server      Server is listening on [ 127.0.0.1 <ipv4> 1434].   
```


If you cant find docker logs, then look in the sql log

![image](https://user-images.githubusercontent.com/44235289/125083876-cd70da80-e0c0-11eb-8aa7-4b19a260d418.png)


---

Regarding instance name, you can use 'localhost\instance' to connect to named instance

**Comment by na-am** [comment]
this is the log from the docker container:
![image](https://user-images.githubusercontent.com/47410115/125092245-6e679180-e0d1-11eb-8ca2-9d68781e7627.png)

**Comment by na-am** [comment]
there is no port given in the settings of  Data Studio:
![image](https://user-images.githubusercontent.com/47410115/125092451-a7a00180-e0d1-11eb-95cd-46c6932dfbe6.png)

**Comment by Steve-Mcl** [comment]
Hi, can you try 3 things please...

![image](https://user-images.githubusercontent.com/44235289/125162850-0f158a00-e182-11eb-9241-c8062480a57a.png)


1. Disable Server Encryption, deploy, test.

2. Remove database name, , deploy, test.

3. Set host name to `IP.ADD.RE.SS\MSSQLSERVER`, deploy, test.

Please be sure to deploy and test after each individual change.

Let me know how you get on.  

Ta.

**Comment by na-am** [comment]
no success, BUT.....   surprise, surprise with native **node** it's working :-)
and yes, encrypt must be false otherwise no connection is possible

> x = sql.connect('Server=10.6.0.89,1433;Database=ms;User Id=nodered;Password=xxx;Encrypt=false')
Promise { <pending> }
> console.dir(x)
Promise {
  ConnectionPool {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _connectStack: [],
    _closeStack: [],
    _connected: true,
    _connecting: false,
    _healthy: true,
    config: {
      options: [Object],
      pool: {},
      port: 1433,
      server: '10.6.0.89',
      database: 'ms',
      domain: undefined,
      user: 'nodered',
      password: 'xxx',
      stream: false,
      parseJSON: false,
      arrayRowMode: false,
      validateConnection: true
    },
    close: [Function: bound globalClose],
    pool: Pool {
      destroyed: false,
      emitter: [EventEmitter],
      creator: [Function: create],
      destroyer: [Function: bound _poolDestroy],
      validate: [Function: bound _poolValidate],
      log: [Function (anonymous)],
      acquireTimeoutMillis: 30000,
      createTimeoutMillis: 30000,
      destroyTimeoutMillis: 5000,
      idleTimeoutMillis: 30000,
      reapIntervalMillis: 1000,
      createRetryIntervalMillis: 200,
      propagateCreateError: true,
      min: 0,
      max: 10,
      used: [],
      free: [],
      pendingCreates: [],
      pendingAcquires: [],
      pendingDestroys: [],
      pendingValidations: [],
      interval: null,
      eventId: 1
    },
    [Symbol(kCapture)]: false
  }
}

**Comment by na-am** [comment]
sorry for wasting your time Steve
now it's working in Node-red
encription=true was one reason AND a faulty syntax in my select statement :-(

**Comment by Steve-Mcl** [comment]
No bother. Glad it's sorted.
