### ISSUE TITLE
Possible to include connection option for ApplicationIntent?

### ISSUE THREAD

**Issue by am-rpa** [bestlong/node-red-contrib-mssql-plus#61]
At first glance I don't see the ability to define the ApplicationIntent. This is needed for Availability Groups with read-only replicas. The connection string value would be "ApplicationIntent=ReadOnly". I don't mind working on a PR as I believe this is supported in Tedious, but want to make sure I'm not overlooking the ability to do this currently.

**Comment by Steve-Mcl** [comment]
Hi, if you are willing to do PR that would be great. 

I suspect you need to add `readOnlyIntent: ` to the [options object](https://github.com/bestlong/node-red-contrib-mssql-plus/blob/f71031fb6b490c20f1ae2d788e5ed15636e3cbce/src/mssql.js#L277) (and set it's value from a new option in the config node)

**Comment by bestlong** [comment]
https://github.com/tediousjs/node-mssql/issues/400
