### ISSUE TITLE
Problem connecting to mssql express

### ISSUE THREAD

**Issue by mc03225** [bestlong/node-red-contrib-mssql-plus#63]
I have a local install of mssql express but I cannot connect. I tried windows authentication, then I tried creating a user, but I cannot connect either way. I have checked that mssql express service is running, and I even set the TCP/IP port to 1433, not that this should matter. So far I have not found a way to connect. To get started,  I just want to create an inject node with a simple insert query into an existing table. Can you help?

**Comment by Steve-Mcl** [comment]
questions... 
* Is the SQL Server on the same server/computer as node-red?
* Can you connect to the instance using SQL Server Management Studio using SQL Login (not integrated)?
* Is the install an instance? 

If you can connect using SSMS using SQL Login, show me the details you used for the SSMS login And a screenshot of the MSSQL-PLUS connection config  (NOTE: Obviously, mask out any sensitive info)

**Comment by oobyx** [comment]
Same problem here

- SQL Server is not on the same server/computer, but in the local network (firewall settings are done - works fine for years with some other MS Windows Client - PCs)
- The install is an instance 
- I can connect the instance using SSMS and SQL Login

<img width="392" alt="sql" src="https://user-images.githubusercontent.com/101604840/158272225-330702b6-5d94-4da2-bbdd-9876ef060a5b.png">
<img width="434" alt="sql2" src="https://user-images.githubusercontent.com/101604840/158272720-f36c69a8-09f2-411f-ab3a-1ce7740a132c.png">
n

**Comment by Steve-Mcl** [comment]
AHH. I don't know why I forgot this. 

An instance doesn't get port 1433 

Connect to your SQL server and check the start up log. You should see the port number assigned. Try using that instead of 1433. 

Please let me know if this works for you.

**Comment by oobyx** [comment]
Thanks Steve! It works - it was Port: 59960!

**Comment by Steve-Mcl** [comment]
@mc03225 can you try this please?

**Comment by mc03225** [comment]
HI Stephen,

Tried, and some other variations but still unable to connect, anything else I can try?

**Comment by mc03225** [comment]
Hi,

Just realised that my instance might be on another port so I checked and found mine was 57708, so I tried and this still failed to connect.
![config](https://user-images.githubusercontent.com/45171925/158372623-fe73fbb0-d644-4e0a-9ae3-a8e344a71ac1.PNG)

**Comment by Steve-Mcl** [comment]
@mc03225 when I said can you try this

> @mc03225 can you try this please?

I meant try this: https://github.com/bestlong/node-red-contrib-mssql-plus/issues/63#issuecomment-1067390539

**Comment by mc03225** [comment]
Hi,

Okay, many thanks - that worked. See screenshot :)

![db-node-red](https://user-images.githubusercontent.com/45171925/158553427-066ee065-33d3-4108-9a89-a2903cf35a6e.PNG)

**Comment by Steve-Mcl** [comment]
Glad it's ok.

**Comment by mc03225** [comment]
Hi,

Thanks for getting back to me so quickly. I am a teacher and I currently show the students sqlite but I would prefer sqlserver express. To this end I simply downloaded a copy server management studio and sqlserver express onto my laptop as a local install with Windows Authentication. Yes, Node-Red is on the Windows laptop.

***@***.***

I created a few databases for testing, I wanted to try connecting Dev with Node-Red

***@***.***

I get failed to connect

***@***.***


***@***.***

The following is the latest try, I tried various combinations. No user name or password, tried localhost, without and with port number. No luck.

***@***.***

I also checked services to check that sqlexpress is running, and it is. This I also used server configuration manager and added port 1433. I know that this is for remote connection but I was getting a bit desperate.

Would be grateful for any help or guidance. Don’t want to use Azure or SqlServer 201x (too much for my needs)

***@***.***


Let me know if you need anything else.

Kind regards
Anwar





Here is my config for the node:

**Comment by Steve-Mcl** [comment]
@mc03225 you should visit the page on GitHub. Much of your reply is messed up. You might want to redo it
