### ISSUE TITLE
Parse mustache feature toggle Big Problem

### ISSUE THREAD

**Issue by softy2k** [bestlong/node-red-contrib-mssql-plus#69]
I really appreciate what you are doing, but I had a big problem with the latest version **v0.10.0**
More precisely with :` feat: Parse mustache feature toggle`

This option should have been active by default. I have a lot of nodes that use mustache and after updating to version **v0.10.0**, they no longer work correctly. Instead of the value from the variables, texts with the names of the variables were inserted. And in the case of SQL columns with numbers, I was getting an insert error.

**Lost data, altered data, blocked nodes, etc**
 
In my case, it is not a solution to manually tick the option: `Parse mustache feature toggle` for each sql node (there are too many, there is a risk of omitting some of them).

**Comment by bestlong** [comment]
Hi @softy2k 

Sorry for the trouble

If flow has been deployed so that the Parse Mustache option has been written into `flow.json`.

You can open flow.json with an editor and replace `"parseMustache": false,` with `"parseMustache": true,`.

Remember to back up before modifying.

**Comment by softy2k** [comment]
For now I'm back to **0.9.1**

I will test the new version in the following days, now I am trying to solve the problems with the lost/altered data.
