### ISSUE TITLE
Instance Name

### ISSUE THREAD

**Issue by fioronileo** [bestlong/node-red-contrib-mssql-plus#75]
Would it be possible to add the ability to configure the SQL node with the instance name? The resulting connection string should be "mssql-server-name\instance-name"

**Comment by Steve-Mcl** [comment]
It is already possible to connect to an instance.

Read this thread: https://github.com/bestlong/node-red-contrib-mssql-plus/issues/63#issuecomment-1067390539

**Comment by fioronileo** [comment]
Yes it works !
Standard instance uses Udp port 1434
