### ISSUE TITLE
Multiple queries doesn't show multiple record set

### ISSUE THREAD

**Issue by Ubbialil** [bestlong/node-red-contrib-mssql-plus#76]
I'm trying to execute a multiple query but the node return only one recordset instead of two.

**Node**
![image](https://user-images.githubusercontent.com/113444554/237035378-f05e96c3-8df8-4580-9224-f977e1c9dcfc.png)

```sql
PRINT 'start'

SELECT TOP 5 * 
FROM SBODemoIT.dbo.[OITM]

SELECT TOP 5 *
FROM SBODemoIT.dbo.[OCRD]

PRINT 'complete'
```

**Return**
As you can in the following screenshot it return only one recordset (array(5)) instead of two recordsets.

![image](https://user-images.githubusercontent.com/113444554/237036939-686aa93d-4e37-4017-be80-abcbabebb5da.png)

The sqlinfo property is filled correctly with the 2 prints.

**Comment by Steve-Mcl** [comment]
To get multiple record sets, chose driver output. 

The "Original Output" mode is for backwards compatibility for those upgrading from node-red-contrib-mssql which never supported this feature.
