### ISSUE TITLE
Does not install with nodejs 20 (@azure/msal-node issue)

### ISSUE THREAD

**Issue by colinl** [bestlong/node-red-contrib-mssql-plus#77]
Version 0.10.2 will not install with nodejs 20.4.0 on Ubuntu 20.04.  The dependency @azure/msal-node requires nodejs 10,12,14,16 or 18.  The error when attempting to install is
```
~/.node-red$ npm install node-red-contrib-mssql-plus
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.18.0',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.4.0', npm: '9.7.2' }
npm WARN EBADENGINE }

```

**Comment by jfaigan** [comment]
FYI, I am having the same issue.
![image](https://github.com/bestlong/node-red-contrib-mssql-plus/assets/14929031/91ee994f-c678-4f2e-aeda-66508a890278)

**Comment by jfaigan** [comment]
I was able to bypass the issue by manually installing the npm package and omitting the --engine-strict flag

npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production  node-red-contrib-mssql-plus@0.10.2

**Comment by bestlong** [comment]
@colinl 
try `npm i node-red-contrib-mssql-plus@0.11.0-beta`

**Comment by bestlong** [comment]
about @azure/msal-node

1.18.3 support

```
  "engines": {
    "node": "10 || 12 || 14 || 16 || 18"
  }
```

^2.0.0 support

```
  "engines": {
    "node": "18 || 20"
  }
```

upgrade is not good decision

suggest use nodejs latest LTS version.

**Comment by colinl** [comment]
Sorry, I did not receive a notification of your earlier message asking me to try the beta version.
Nodejs 20 is overdue to become the current LTS (https://nodejs.dev/en/about/releases/) so presumably it will be announced as LTS very soon.
You could release your node as a new major version, requiring 18 or 20.

**Comment by bestlong** [comment]
wait https://github.com/tediousjs/tedious/pull/1575 PR merge

**Comment by Steve-Mcl** [comment]
This is long since resolved as far as I can see?

**Comment by Steve-Mcl** [comment]
Yes, and that will happen (soon), but for now semver will do the job.
