### ISSUE TITLE
Bulk insert does not work.

### ISSUE THREAD

**Issue by belgianbeer** [bestlong/node-red-contrib-mssql-plus#79]
I installed Nod-RED with node-red-contrib-mssql-plus.

After installed node-red-contrib-mssql-plus, I tested the "Bulk demo.json". (BTW, this example looks not in module. I got it from repository of Github.)

"Create demo_device_parameters_table" and "Drop demo_device_parameters_table" work well. But inject "raws:1000" has error. Here is error message.

```
11 Sep 10:46:51 - [info] [MSSQL-CN:My SQL Server connection] Error connecting to server : sake-tank-db0-svr.database.windows.net, database : sake-tank-db0, port : 1433, user : sakesqlmaster
RequestError: Invalid string.
    at BulkLoad.done [as callback] (/var/lib/nodered1/.node-red/node_modules/mssql/lib/tedious/request.js:307:19)
    at Parser.onEndOfMessage (/var/lib/nodered1/.node-red/node_modules/tedious/lib/connection.js:2823:22)
    at Object.onceWrapper (node:events:627:28)
    at Parser.emit (node:events:513:28)
    at Readable.<anonymous> (/var/lib/nodered1/.node-red/node_modules/tedious/lib/token/token-stream-parser.js:32:12)
    at Readable.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EREQUEST',
  originalError: TypeError: Invalid string.
      at Object.validate (/var/lib/nodered1/.node-red/node_modules/tedious/lib/data-types/nvarchar.js:146:13)
      at RowTransform._transform (/var/lib/nodered1/.node-red/node_modules/tedious/lib/bulk-load.js:116:26)
      at Transform._write (node:internal/streams/transform:175:8)
      at writeOrBuffer (node:internal/streams/writable:392:12)
      at _write (node:internal/streams/writable:333:10)
      at Writable.write (node:internal/streams/writable:337:10)
      at Readable.ondata (node:internal/streams/readable:766:22)
      at Readable.emit (node:events:513:28)
      at Readable.read (node:internal/streams/readable:539:10)
      at flow (node:internal/streams/readable:1023:34),
  number: undefined,
  lineNumber: undefined,
  state: undefined,
  class: undefined,
  serverName: undefined,
  procName: undefined,
  precedingErrors: []
}
11 Sep 10:46:51 - [error] [MSSQL:bulk insert -> demo_device_parameters_table] Invalid string.
```

Simple INSERTs and SELECTs are working fine.

My environment as follows.

- Debian 12 (Linux 6.1.0-11, VM on Azure)
- Azure SQL Database
- Node.js  version: v18.13.0
- Node-RED version: v3.1.0

Am I misunderstanding something?

**Comment by Steve-Mcl** [comment]
Works for me


https://github.com/bestlong/node-red-contrib-mssql-plus/assets/44235289/7bd35c59-718e-4d13-8f8d-535b01cd4020

Unfortunately, I do not have access to an azure DB so I used a linux docker image

**Comment by belgianbeer** [comment]
I created another server and prepared a docker environment. I started the docker version of Node-RED and tested it. But the same error occurred. What am I doing wrong?

**Comment by belgianbeer** [comment]
I created another server and prepared a docker environment. So I started the docker version of Node-RED and tested it.
After starting Node-RED docker, I added "node-red-contrib-mssql-plus" and loaded and executed the demo.
"Create demo_device_parameters_table" and "Drop demo_device_parameters_table" worked fine. But "bulk insert -> demo_device_parameters_table" gave the same error.

**Comment by Steve-Mcl** [comment]
> I created another server (not on Azure)

Can you link to the exact image you used please

**Comment by belgianbeer** [comment]
I used the following command line when starting Node-RED:

```
docker run -it -p 1880:1880 -v node_red_data:/data --name mynodered nodered/node-red
```

It's probably https://hub.docker.com/r/nodered/node-red

**Comment by Steve-Mcl** [comment]
> I used the following command line when starting Node-RED:
> 
> ```
> docker run -it -p 1880:1880 -v node_red_data:/data --name mynodered nodered/node-red
> ```


I was referring to Azure:

> > I created another server (not on Azure)
> 
> Can you link to the exact image you used please

as in when you created ANOTHER SERVER - which docker image did you use?


---


However: Since I ss you are also using docker for Node-RED - are you in a position to test against Azure with node-red natively/on metal?

**Comment by belgianbeer** [comment]
I will sort out the situation.

First reported configuration:

- I created a new Azure VM and Azure SQL Database.
- The VM Image is Debian 12 "Bookworm".
- SQL Database is configured without domain authentication.
- The VM installed nodejs with apt after starting Debian.
- I installed npm with apt.
- I installed Node-RED using npm. (npm install --unsafe-perm --global Node-RED)
- The other thing I did was install nginx and configure Node-RED with a reverse proxy for SSL.
- I installed node-red-contrib-mssql-plus after starting Node-RED.
- I did a test.

Second reported configuration:

- I prepared one more new Azure SQL Database for testing.
- SQL Database is set to not perform domain authentication.
- I had a Debian 11 VM on my office server that I usually use, so I installed Docker on it.
- I ran a Node-RED Docker image.
- I installed and tested node-red-contrib-mssql-plus after starting Node-RED.

I can also set up a metal server if needed. I'm thinking of using the first configuration in the project I'm currently working on, so I'd really like to resolve any issues with node-red-contrib-mssql-plus.

**Comment by Steve-Mcl** [comment]
> * I had a Debian 11 VM on my office server that I usually use, so I installed Docker on it.

It would be very useful to know if you could install Node-RED on the VM (this should work as "on metal") and try again.

And since your VM is Debian, can I ask that you install Node-RED using the official installer script with `--node18` appended to the command. see here: https://nodered.org/docs/getting-started/raspberrypi#installing-and-upgrading-node-red

**Comment by belgianbeer** [comment]
I have prepared a Debian Bullseye metal server. After that I installed nodejs 18.18.
I installed Node-RED using the Raspberry Pi script in that URL.
I ran the same test after starting Node-RED and got the same error regarding bulk insert.
I will continue to try changing the nodjs version to 16.

**Comment by belgianbeer** [comment]
It worked!
But, It wat not my mistake. The example was bad. If I use the sample as is, the type of the fifth parameter in the bulk insert flow was NVarChar(200). But I think this should be a Float.

![2023-09-25 142434](https://github.com/bestlong/node-red-contrib-mssql-plus/assets/20077924/354a25e1-b41e-45b2-80ef-e66995292769)

**Comment by belgianbeer** [comment]
I created a pull request for fix this issue.

**Comment by belgianbeer** [comment]
Thank you!
