### ISSUE TITLE
I would need "ApplicationIntent=ReadOnly" in the SQL connection string

### ISSUE THREAD

**Issue by JL400** [bestlong/node-red-contrib-mssql-plus#80]
I'm using node-red-contrib-mssql-plus
Is there an option to add additionnal parameters in the connection string?
I need to add "ApplicationIntent=ReadOnly" to connect to a read only db.
Could you please support this?

**Comment by bestlong** [comment]
duplicate #61

**Comment by JL400** [comment]
Hi, Great Function, it works thanks
Just a detail, the the ApplicationIntent=ReadOnly is activated when checkbox is false, is this on purpose?

**Comment by bestlong** [comment]
fix: v0.12.1
