### ISSUE TITLE
What does it do that the one it is based on doesn't

### ISSUE THREAD

**Issue by ukmoose** [bestlong/node-red-contrib-mssql-plus#9]
The ReadMe states the node it is based on, but doesn't say what it does that the other one doesn't.   

What can I do in your node that I can't do in the other?

**Comment by bestlong** [comment]
Hi @ukmoose 

Thanks for your comments.

node-red-contrib-mssql has stopped maintenance for a long time

so, i create node-red-contrib-mssql-plus increase the features I need and publish.

I will update ReadMe info.

**Comment by youngkzy** [comment]
Hi @bestlong,  Can you fix the issues which are related to ES6 Javascript where the older connections are cached?  the configuration then don't update and then don't match the queries being run.   I have 2 different Databases on 2 Different SQL Servers.  I connect to both for the first time fine.   Upon running the flow again, I get a SQL error where it cannot find the table in the query.  The reason being is that the connection configuration is not being updated against the information in the connection part of the MSSQL Node... "node-red-contrib-mssql-plus".  Please.

**Comment by Steve-Mcl** [comment]
> Hi @bestlong, Can you fix the issues which are related to ES6 Javascript where the older connections are cached? the configuration then don't update and then don't match the queries being run. I have 2 different Databases on 2 Different SQL Servers. I connect to both for the first time fine. Upon running the flow again, I get a SQL error where it cannot find the table in the query. The reason being is that the connection configuration is not being updated against the information in the connection part of the MSSQL Node... "node-red-contrib-mssql-plus". Please.

Fixed in V0.2.1
