### ISSUE TITLE
Older SQL Node are not properly configured

### ISSUE THREAD

**Issue by softy2k** [bestlong/node-red-contrib-mssql-plus#94]
About 5 years ago I created a flow with various nodes, including some nodes with SQL.
Over time, I updated nodeJS, Node-Red etc.

**Most of the SQL nodes are unchanged in the editor (about 5 years old).**
Now, if I want to edit any old SQL node, I get the error:
```
The workspace contains some nodes that are not properly configured:
     [Home] Test (MSSQL)
Are you sure you want to deploy?
```

![NodeError](https://github.com/bestlong/node-red-contrib-mssql-plus/assets/37790195/82dbd5aa-a7a0-40fb-9647-bd942fc84d6b)

So, it is enough just to edit a SQL node (**Edit MSSQL node**), click randomly in the open editing window) even without changing anything, and then when I press the **Done** button I receive the message `The workspace contains some nodes that is not properly configured`.

The machine on which the flow runs:
- NodeRed 3.1.5
- NodeJS 18.19.1
- node-red-contrib-mssql-plus 0.12.2
- Windows Server x64 (same issue on Ubuntu)

The SQL node runs without problems, only this disturbing message appears. And if I refresh the page in the browser, the error message disappears, but reappears if I try to edit the respective SQL node again. Most likely this bug is quite old.

I am also attaching a sample of the exported node: [OldSqlNode.json](https://github.com/bestlong/node-red-contrib-mssql-plus/files/14369992/OldSqlNode.json)

**Comment by bestlong** [comment]
Hi @softy2k 
change SQL node Output property from [realmin] to [payload]
then deploy flow and reflash browser.

**Comment by softy2k** [comment]
Nothing changed, some issue...

**Comment by Steve-Mcl** [comment]
5 years is a very long time and it is possible something that changed in the node or config node does not have a clean and direct in-place upgrade. 

My recommendation is:
Open the node, edit the config node, press done on the config node, press done on the mssql node. Deploy, refresh. 

If that doesn't work, delete the config node and add a new one (it can be set exactly the same)

Let me know if that solves it please.

**Comment by softy2k** [comment]
If I create a new SQL node ... all is OK.
But I have a few dozen old SQL node. To manually edit each one separately would take me too much time.

**Comment by Steve-Mcl** [comment]
Also, export a good node and a bad node. See what the differences are. It will be helpful for us to fix something broke and to provide you with a quick fix.

**Comment by softy2k** [comment]
In Old node I have :   ` "rows": ""`
If I change in file to `"rows": "rows"` , it seems to work

**Comment by softy2k** [comment]
Can I help with anything else?

**Comment by Steve-Mcl** [comment]
Hey @softy2k I think that is enough to see what is going on. 

Tbh, this is quite the edge case and your fix has been recorded in this issue so if one of us don't get around to handling this large step upgrade issue, at least there is a way to get up and running.

**Comment by caccia86** [comment]
Hi, just for notice I also encountered the same issue and I temporarily resolved with the workaround. (https://github.com/bestlong/node-red-contrib-mssql-plus/issues/94#issuecomment-1959113621).

**Comment by softy2k** [comment]
I'm still waiting for a fix (new release)

**Comment by Steve-Mcl** [comment]
See this thread for how to get working with Node 20

https://discourse.nodered.org/t/unsupported-engine/88759/7?u=steve-mcl
